import { DevLinkProvider, NewNav } from "@/devlink";
import "@/devlink/global.css";
import styles from "./globals.css";
import "@/utils/font.css";

export const metadata = {
  title: "Khue Pham",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DevLinkProvider>
          <div className={styles.wrapper}>
            <NewNav
              home={{ href: "/" }}
              blog={{ href: "/blog" }}
              portfolio={{ href: "/portfolio" }}
              contact={{ href: "/contact" }}
            />
            {children}
          </div>
        </DevLinkProvider>
      </body>
    </html>
  );
}
